### ISSUE TITLE
New Garden Agitproper: AGIT cannot initiate price oracle or execute proposals

### ISSUE THREAD

**Issue by cadillion** [1Hive/gardens#520]
Hi there,

We started a new garden but we can't execute any proposals even though we have sufficient support and the conviction period has elapsed; the transaction just returns as reverted. Based on the docs and the past Github issues, I suspect it's because we cannot execute the price oracle contract.

On latest Chrome Incognito with a Ledger on xDai via Metamask, the price oracle immediately returns an error with the following JSON-RPC error:

```
{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": -32015,
        "message": "revert"
    },
    "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32015,\n    \"message\": \"revert\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:95847)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:96879\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:12923"
}
```

Please advise.

**Comment by 0xGabi** [comment]
Hi @cadillion thanks for the report, this was related to the gas limit of the transaction. We include a fix a few days ago: https://github.com/1Hive/gardens-ui/pull/811

We merge it to the production branch now, will be ready in a couple of minutes.
