### ISSUE TITLE
An unexpected error has occurred (day 3)

### ISSUE THREAD

**Issue by ddan4** [1Hive/gardens#552]
using https://rpc.gnosischain.com trying to connect here:

https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8/proposal/38

tried both firefox and chrome...  (disabled any ad blockers)

Interestingly, I can connect on the homepage, but when I navigate to the proposal (even after reloading the page) it doesn't recognize me as being connected.

I'm worried about getting a vote in, and wondering if I'm the only one unable to connect on this proposal, currently.

same as these https://github.com/1Hive/gardens/issues/432 https://github.com/1Hive/gardens/issues/530 https://github.com/1Hive/gardens/issues/547

**Comment by ddan4** [comment]
when I click this appears in the console
```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'find')
    at ProposalDetail.js:129:24
    at Object.yo [as useMemo] (react-dom.production.min.js:162:119)
    at t.useMemo (react.production.min.js:25:113)
    at qe (ProposalDetail.js:120:25)
    at Qa (react-dom.production.min.js:153:146)
    at Fo (react-dom.production.min.js:175:309)
    at Es (react-dom.production.min.js:263:406)
    at yu (react-dom.production.min.js:246:265)
    at vu (react-dom.production.min.js:246:194)
    at su (react-dom.production.min.js:239:172)
is @ react-dom.production.min.js:209
a.componentDidCatch.n.callback @ react-dom.production.min.js:227
va @ react-dom.production.min.js:131
cs @ react-dom.production.min.js:212
wu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
qi @ react-dom.production.min.js:122
_u @ react-dom.production.min.js:248
su @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
qi @ react-dom.production.min.js:122
Ki @ react-dom.production.min.js:123
Yi @ react-dom.production.min.js:122
nu @ react-dom.production.min.js:230
bo @ react-dom.production.min.js:163
(anonymous) @ core.esm.js:356
Promise.then (async)
(anonymous) @ core.esm.js:351
Promise.then (async)
(anonymous) @ core.esm.js:350
m @ core.esm.js:123
(anonymous) @ core.esm.js:346
(anonymous) @ index.js:2160
l @ index.js:217
(anonymous) @ index.js:448
(anonymous) @ index.js:273
R @ index.js:8
o @ index.js:30
Promise.then (async)
R @ index.js:18
o @ index.js:30
(anonymous) @ index.js:37
(anonymous) @ index.js:26
(anonymous) @ index.js:2241
(anonymous) @ Wallet.js:116
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Wallet.js:113
(anonymous) @ AccountModule.js:51
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ AccountModule.js:48
(anonymous) @ ScreenProviders.tsx:108
s @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
ht @ react-dom.production.min.js:56
B @ react-dom.production.min.js:287
z @ react-dom.production.min.js:19
Xt @ react-dom.production.min.js:70
Jt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qi @ react-dom.production.min.js:122
D @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
```

**Comment by ddan4** [comment]
I've now tried with chain list a number of different rpc...
https://chainlist.org/?search=gnosis

I'm on brave, and firefox.. maybe  I should try chromium instead, or even pure chrome

**Comment by ddan4** [comment]
ok, finally got working in plain jane chrome browser... not so sure this should be closed, but at least I have peace :D

**Comment by kamikazebr** [comment]
Closing it
